### ISSUE TITLE
bug: SafeTransferLib

### ISSUE THREAD

**Issue by obatirou** [huff-language/huffmate#119]
[This PR](https://github.com/huff-language/huffmate/pull/118) uncover a bug in `SafeTransferLib` by fixing the fuzzing.

This needs investigation.

<img width="1234" alt="Capture d’écran 2023-03-24 à 20 01 38" src="https://user-images.githubusercontent.com/92337658/227616802-d77b427d-4098-4149-8fd2-8ced4666ad52.png">

**Comment by cheethas** [comment]
Its interesting that merging the above pr did not break ci, do you know your current fuzzer seed?

**Comment by clabby** [comment]
I don't believe this is a bug, but thank you for reporting 😄 

If you notice, the `to` address is the [Hardhat console address](https://github.com/foundry-rs/forge-std/blob/master/src/Base.sol#LL11C17-L11C17), and that contract is not rejected by the test because it has no code (foundry hooks into it when it receives a call, and [reverts if no selectors match](https://github.com/foundry-rs/foundry/blob/f2d0d839b149082dc4838fe43ed84713d98e7361/evm/src/executor/inspector/logs.rs#L24-L32)).

We should fix up this test to exclude the console and VM addresses.

**Comment by obatirou** [comment]
> I don't believe this is a bug, but thank you for reporting 😄
> 
> If you notice, the `to` address is the [Hardhat console address](https://github.com/foundry-rs/forge-std/blob/master/src/Base.sol#LL11C17-L11C17), and that contract is not rejected by the test because it has no code (foundry hooks into it when it receives a call, and [reverts forcefully if no selectors match](https://github.com/foundry-rs/foundry/blob/f2d0d839b149082dc4838fe43ed84713d98e7361/evm/src/executor/inspector/logs.rs#L24-L32)).
> 
> We should fix up this test to exclude the console and VM addresses.

Oh you’re right, thank you !
I should have not labeled this issue as a bug without looking into it a little bit. Unfortunately, did not have time when discovering this failing test.
It should have been tagged as a failing test and not a bug until confirmation.
I will make sure to pay more attention next time !

**Comment by clabby** [comment]
> > I don't believe this is a bug, but thank you for reporting smile
> > If you notice, the `to` address is the [Hardhat console address](https://github.com/foundry-rs/forge-std/blob/master/src/Base.sol#LL11C17-L11C17), and that contract is not rejected by the test because it has no code (foundry hooks into it when it receives a call, and [reverts forcefully if no selectors match](https://github.com/foundry-rs/foundry/blob/f2d0d839b149082dc4838fe43ed84713d98e7361/evm/src/executor/inspector/logs.rs#L24-L32)).
> > We should fix up this test to exclude the console and VM addresses.
> 
> Oh you’re right, thank you ! I should have not labeled this issue as a bug without looking into it a little bit. Unfortunately, did not have time when discovering this failing test. It should have been tagged as a failing test and not a bug until confirmation. I will make sure to pay more attention next time !

No worries! Better safe than sorry, much appreciated.
