### ISSUE TITLE
fix: `SafeTransferLib` tests

### ISSUE THREAD

**Issue by clabby** [huff-language/huffmate#120]
# Overview

In `SafeTransferLib`'s tests, we don't currently exclude the [hardhat console](https://github.com/foundry-rs/forge-std/blob/master/src/Base.sol#LL11C17-L11C17) or [vm](https://github.com/foundry-rs/forge-std/blob/master/src/Base.sol#L9) addresses from the non-contract tests. As pointed out in #119, this can sometimes cause the fuzz tests to fail.

## Solution

Exclude the [hardhat console](https://github.com/foundry-rs/forge-std/blob/master/src/Base.sol#LL11C17-L11C17) or [vm](https://github.com/foundry-rs/forge-std/blob/master/src/Base.sol#L9) addresses from the non-contract tests. Bonus points for replacing the parameter restrictions with `vm.assume` so we get full advantage of all fuzz runs.

**Comment by rabib** [comment]
This issue also affects `testFuzzTransferETH(...)`.

```
Failing tests:
Encountered 1 failing test in test/utils/SafeTransferLib.t.sol:SafeTransferLibTest
[FAIL. Reason: ETHTransferFailed() Counterexample: calldata=0xb91b6ee7000000000000000000000000000000000000000000636f6e736f6c652e6c6f670000000000000000000000000000000000000000000000000000000000000492000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000a0a, args=[0x000000000000000000636F6e736F6c652e6c6f67, 1170, 0x0000000000000000000000000000000000000000000000000000000000000a0a]] testFuzzTransferETH(address,uint256,bytes) (runs: 179, μ: 41692, ~: 43294)
```
