### ISSUE TITLE
Shouldnt the ERC721 implementation revert on `ownerOf(address(0))`?

### ISSUE THREAD

**Issue by eugenioclrc** [huff-language/huffmate#125]
This is a quote from [eip-721](https://eips.ethereum.org/EIPS/eip-721)

> /// @notice Find the owner of an NFT
> /// @param _tokenId The identifier for an NFT
> /// @dev NFTs assigned to zero addresses are considered invalid, and queries
> /// about them do throw.
> /// @return The address of the owner of the NFT
> function ownerOf(uint256 _tokenId) external view returns (address);

I dig into other implementations and see that `ownerOf(address(0))` reverts;
- OZ [ERC721.sol#L72](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L72)
- Solmate [ERC721.sol#L36](https://github.com/transmissions11/solmate/blob/main/src/tokens/ERC721.sol#L36)
- Solady [ERC721.sol#L130-L134](https://github.com/Vectorized/solady/blob/main/src/tokens/ERC721.sol#L130-L134)

But in the `Huffmate` implementation is returning always `0`, shoulndt revert instead?
Please view [ERC721.t.sol#L821-L824](https://github.com/huff-language/huffmate/blob/main/test/tokens/ERC721.t.sol#L821-L824)

**Buttplug**

**Comment by MathisGD** [comment]
Do you mean that the view function returning the owner of a given tokenId should revert when the "owner" is address zero ? If yes it seems that your are right.
