### ISSUE TITLE
fix: Dynamic Constructor Args

### ISSUE THREAD

**Issue by refcell** [huff-language/huffmate#63]
## Overview

Tokens currently don't use dynamic constructor arguments, but rather static strs.

**Comment by MathisGD** [comment]
Do you mean that `symbol` and `name` should be stored in storage ? This would mean that they would be more expensive to get, whereas constant could be set at compilation (https://github.com/huff-language/huff-rs/pull/171).

**Comment by yorhodes** [comment]
@MathisGD my guess is "immutables" eg constructor arguments "stored" in bytecode

**Comment by refcell** [comment]
Implemented by the 🐐 @MathisGD in #89
